### ISSUE TITLE
Refactoring namespace'ów w warstwie modeli

### ISSUE THREAD

**Issue by felskit** [bdach/knowledge-representation#24]
Wypadałoby przeorganizować strukturę warstwy modeli, aby namespace'y odpowiadały tym, które są w warstwie UI.

ReSharper zrobi to automagicznie, tylko trzeba to zrobić w taktycznym momencie, aby nie popsuć nikomu ich rozgrzebanych ficzerów i wmerge'ować to od razu do mastera, aby każdy sobie sam mastera wmerge'ował do siebie (inaczej konflikty jak siemano).

**Comment by bdach** [comment]
WONTFIX  ¯\_(ツ)_/¯
