### ISSUE TITLE
Niezależne fluenty nieinertne

### ISSUE THREAD

**Issue by AwesomePatrol** [bdach/knowledge-representation#43]
Dodanie nieinertnego fluenta (niezależnego od innych) zmienia rezultat kwerendy accessible.

![gr_1_accessible_4](https://user-images.githubusercontent.com/8083990/40585325-df395b6c-61b0-11e8-87a8-066d8c584040.PNG)
![gr_1_accessible_3](https://user-images.githubusercontent.com/8083990/40585324-df1b036a-61b0-11e8-9b9c-458900f0f118.PNG)

**Comment by bdach** [comment]
Potwierdzam, reprodukowalne w edytorze, jak i w gramatyce. Zaczynam grzebanie.

**Comment by bdach** [comment]
Wypchnąłem powyższy fix (razem z testem na reprodukcję) na gałąź [`bugfix/query-evaluation-logic`](https://github.com/bdach/knowledge-representation/tree/bugfix/query-evaluation-logic).

**Comment by michalk355** [comment]
@bdach masz rację to tutaj jest błąd i twój fix jest spoko. Nie wiem co mi sie ubzduralo ze musi byc sciezka z kazdego stanu
