### ISSUE TITLE
Program się zawiesza

### ISSUE THREAD

**Issue by AwesomePatrol** [bdach/knowledge-representation#44]
W pewnych sytuacjach użycie specjalnych formul powoduje zawieszenie się programu.

Załączona jest próba reprodukcji problemu. Jedna z kwerend nie wykonuje się. Widoczne rezultaty są pozostałością poprzedniego wykonania kiedy `consumeA` oraz `consumeB` nie zostały jeszcze dodane. Po prawej stronie widać, ze jeden rdzen jest zajęty w 100%. Mam zapisany scenariusz jakby ktoś chciał.

![gr_1_accessible_hang](https://user-images.githubusercontent.com/8083990/40585577-ab39a2ea-61b5-11e8-9b22-11bda12e66f0.PNG)

**Comment by grajekf** [comment]
Jak mógłbyś wstawić ten scenariusz to byłbym bardzo wdzięczny :)

**Comment by grajekf** [comment]
Mam wrażenie że tutaj problemem jest wykładnicza złożoność, ale jeszcze to badam. Po prostu dla tego przypadku jest aż 32 różnych akcji, a stanów jest 8, co daje rekursję o głębokości 8 i branching factor 32, co daje pesymistycznie 1 099 511 627 776 wywołań rekurencyjnych. Dla programów z mniejszą ilością akcji (tak jak u was przed consumeA i consumeB) kończy się, bo dużo mniej możliwych akcji jest.

**Comment by AwesomePatrol** [comment]
Bardzo możliwe, ze "1 099 511 627 776 wywołań rekurencyjnych" tyle zajmuje ;)
Po 5 minutach stwierdziłem, ze to pewnie zwiecha.

ZIP aby github łyknął.
[scenario-20180527T115429Z.zip](https://github.com/bdach/knowledge-representation/files/2065403/scenario-20180527T115429Z.zip)

**Comment by AwesomePatrol** [comment]
Jak usunąłem dwie ostatnie kwerendy to od razu się wykonało. Ponowne dodanie drugiej kwerendy znowu zawiesiło program.

**Comment by bdach** [comment]
W trakcie jest opcja anulowania obliczeń (`bugfix/dynamic-system-hang`)
