### ISSUE TITLE
Zespół #3 - przetestowanie aplikacji

### ISSUE THREAD

**Issue by bdach** [bdach/knowledge-representation#46]
Wreszcie otrzymałem od zespołu nr 3 aplikację.

Link: https://1drv.ms/f/s!Au2yGRms8nYDjw8Qi6yJHNJ9dOHa

Trzeba ją przetestować i najlepiej znaleźć jakieś błędy. Pamiętajcie, że stopień przetestowania też będzie częścią oceny, więc mimo tego, że dostaliśmy aplikację późno, musimy to zrobić w miarę porządnie.

**Comment by bdach** [comment]
# Edytor nie wyświetla zmian w formułach i kwerendach

## Opis problemu

Gdy używam przycisku do edycji zmian przy formułach (![edit](https://user-images.githubusercontent.com/20418176/40936637-4195ae1e-683c-11e8-889c-7daa20e3b6f0.png)) i wprowadzam zmiany, nie są one wyświetlane w głównym widoku aplikacji.

## Kroki reprodukcji

1. Dla dowolnej istniejącej formuły wybieram przycisk ![edit](https://user-images.githubusercontent.com/20418176/40936637-4195ae1e-683c-11e8-889c-7daa20e3b6f0.png).
2. Zmieniam dowolny element zdania.
3. Wciskam **Ok**.
4. W głównym widoku nie zmienia się etykieta edytowanego zdania. Gdy ponownie wybiorę opcję edycji zdania, wprowadzone wcześniej zmiany są tam widoczne, lecz nie są wyświetlane w głownym widoku/

**Comment by wolskippp** [comment]
# Program crashuje się przy wciśnięciu compute gdy ma pustą liście agentów lub fluentów 
[Brak walidacji inputu] 

## Opis problemu

Przy usunięciu wszystkich agentów, bądź fluentów i wciśnięciu przycisku "Compute" program niespodziewanie się wyłącza.

## Kroki reprodukcji

1. Wyczyść pole "Agents" albo "Fluents" poprzez wciskanie ikony "kosza" przy widocznych elementach na danym polu
2. Wciśnij przycisk "Compute"
3. Program niespodziewanie wyłącza się.

**Comment by michalk355** [comment]
# Można mieć 2 fluenty, akcje lub agentów o tej samej nazwie, ponadto w przypadku 2 fluentów o tej samej nazwie program się crashuje
## Opis problemu
Można dodać nowy fluent o tej samej nazwie co już istniejący. Tak samo z akcjami oraz agentami. Ponadto w przypadku, gdy wciśniemy "Compute" mając 2 fluenty o tej samej nazwie, program się wyłącza.
##Kroki reprodukcji
1. Wcisnąć przycisk "Load history 1"
2. Dodać akcję Load, Agenta S, lub fluent S_i
3. W przypadku gdy dodaliśmy fluent S_i, po kliknięciu "Compute" program wyłącza się

**Comment by michalk355** [comment]
# Początkowo zaznaczone checkboxy przy dodawaniu formuł są interpretowane jako brak zaznaczenia
## Opis problemu
Przy dodawaniu formuly causes, releases lub impossible, przy parametrze pi są domyślnie zaznaczone checkboxy. Mimo tego, jest to interpretowane w polu Result jakby tych zaznaczeń nie było. Dopiero po odznaczeniu i ponownym zaznaczeniu są one interpretowane poprawnie.
## Kroki reprodukcji
1. Wcisnąć przycisk "Load history 1"
2. Wcisnąć przycisk dodawania nowej formuły.
3. Wybrać formułę causes, releases lub impossible.
4. Zauważyć że w polu pi M_l i S_i są domyślnie zaznaczone, ale "if" w polu result jest pusty.
5. Po odznaczeniu i ponownym zaznaczeniu checkboxa i odświeżeniu resulta można zobaczyć w ifie odpowiedni fluent

**Comment by michalk355** [comment]
# Błędny wynik zapytania w historyjce 1, w porównaniu z wynikiem w dokumentacji.
## Opis problemu
W historyjce 1, w dokumentacji zapytanie: "necessary accessible (M_l) from (¬M_l) by {M}" ma wynik False, podczas gdy w programie zwrócone jest True.
## Kroki reprodukcji
1. Wcisnąć przycisk "Load history 1"
2. Wcisnąć przycisk "Compute"
3. Zobaczyć wynik zapytania.

**Comment by wolskippp** [comment]
# Program pozwala na nie wybranie żadnych opcji w momencie edycji kwerendy, po czym crashuje sie przy próbie uruchomienia obliczeń
## Opis problemu
W polu edycji kwerend przy zamianie typu kwerendy i zostawieniu domyślnych wartości program crashuje sie przy compute.

## Kroki reprodukcji

1. Edytuj dowolną kwerende
2. Zmień jej typ
3. Wciśnij "Ok"
4. Wciśnij przycisk "Compute"

**Comment by bdach** [comment]
# Teoria - sprzeczne definicje prawdziwości zdania impossible

## Opis problemu

Na str. 5 dana jest definicja prawdziwości zdania **impossible**:

> Wyrażenie (**impossible** *A* **by** *G* **if** *π*) jest prawdziwe w *S* wtedy i tylko wtedy, gdy
> Ɐ *σ* ⊧ *π* → *Res(A, G, σ)* = {*σ*}

Natomiast ponieważ zdanie

> **impossible** *A* **by** *G* **if** *π*

jest równoważne zdaniu (jest alternatywnym zapisem zdania)

> *A* **by** *G* **causes** ⊥ **if** *π*

z definicji funkcji *Res*<sub>0</sub> wynika, że dla akcji *A* objętej zdaniem **impossible**, pod warunkiem spełnienia warunku wstępnego, dla dowolnego stanu *σ'* następnik implikacji w definicji *Res*<sub>0</sub> jest fałszywy, zatem *Res<sub>0</sub>(A, G, σ)* = *Res(A, G, σ)* = ∅.

**Comment by bdach** [comment]
# Historia 2 - wynik sprzeczny z grafem przejść w teorii

## Opis problemu

Dla przykładu 2. (sekcja 4. w dokumentacji) graf funkcji przejścia (podsekcja 4.7.) pokazuje, że ze stanu *L, P* nie powinno być możliwe osiągnięcie stanu *~L, P* (wszystkie strzałki między tymi dwoma stanami skierowane są w przeciwne strony). Tymczasem, wprowadzenie do programu kwerend dla historii 2. postaci

> **possibly accessible** *(~L, P)* **from** *(L, P)* **by** {*J*}
> **necessary accessible** *(~L, P)* **from** *(L, P)* **by** {*J*}

powoduje uzyskanie dwóch wyników **True**.

## Kroki reprodukcji

1. Ładuję historię #2.
2. Dodaję kwerendy
> **possibly accessible** *(~L, P)* **from** *(L, P)* **by** {*J*}
> **necessary accessible** *(~L, P)* **from** *(L, P)* **by** {*J*}
3. Wciskam przycisk **Compute**.
4. W oknie dialogowym z wynikami widoczna jest odpowiedź **True** na obie kwerendy.

**Comment by bdach** [comment]
# Edytor scenariusza nie pozwala na wyspecyfikowanie dowolnej formuły

## Opis problemu

Dokumentacja specyfikuje, że w zdaniach wartości, obserwacji, ograniczeń i efektu można wstawiać formuły logiczne. Edytor zdań scenariusza pozwala jednak tylko na wstawianie literałów.

## Kroki reprodukcji

1. Dodaję dowolne zdanie wartości, obserwacji, ograniczenia lub efektu.
2. W otwartym oknie dialogowym do edycji nie mogę wyspecyfikować dowolnej formuły logicznej, jedynie literały.

**Comment by andrzejbg** [comment]
# Program crashuje się przy wciśnięciu compute gdy fluenty, akcje, albo agenci nie mają opisu (uzupełnienie poprzednio zgłaszanego błędu)
[Brak walidacji inputu] 

## Opis problemu

Usunięcie wszystkich agentów, formuł i akcji, a następnie dodanie nowych bez opisu, a następnie naciśnięcie przycisku compute powoduje crash programu (ewentualnie dodanie formuł i kwerend nic nie zmienia).

## Kroki reprodukcji

1. Wyczyść pole "Agents", "Fluents" oraz "Actions" poprzez wciskanie ikony "kosza" przy widocznych elementach na danym polu.
2. Dodaj nowe akcje, fluenty i agentów, uzupełniając jedynie pole "Name".
2. Wciśnij przycisk "Compute"
3. Program niespodziewanie wyłącza się.
